using System.Globalization;
using System.Text;

namespace GoldWalletSystem.API.Helpers;

internal static class InvoicePdfTemplateBuilder
{
    public static byte[] Build(string title, IReadOnlyList<(string Label, string Value)> fields)
    {
        var content = new StringBuilder();

        // Page background and centered card
        content.AppendLine("0.95 0.95 0.95 rg");
        content.AppendLine("0 0 595 842 re f");
        content.AppendLine("1 1 1 rg");
        content.AppendLine("28 80 539 700 re f");
        content.AppendLine("0.82 0.82 0.82 RG");
        content.AppendLine("1 w");
        content.AppendLine("28 80 539 700 re S");

        // Header bar
        content.AppendLine("0.13 0.13 0.13 rg");
        content.AppendLine("28 730 539 50 re f");

        WriteText(content, 44, 747, 19, title, 1, 1, 1);
        WriteText(content, 44, 713, 11, "Generated by Gold Wallet", 0.26, 0.26, 0.26);

        content.AppendLine("0.86 0.86 0.86 RG");
        content.AppendLine("1 w");
        content.AppendLine("44 690 m 550 690 l S");

        var currentY = 668d;
        foreach (var field in fields)
        {
            var label = string.IsNullOrWhiteSpace(field.Label) ? "Field" : field.Label.Trim();
            var value = string.IsNullOrWhiteSpace(field.Value) ? "-" : field.Value.Trim();
            var rows = Wrap($"{label}: {value}", 76);

            for (var i = 0; i < rows.Count; i++)
            {
                WriteText(content, 52, currentY, i == 0 ? 12 : 11, rows[i], 0.16, 0.16, 0.16);
                currentY -= 16;
            }

            content.AppendLine("0.90 0.90 0.90 RG");
            content.AppendLine($"52 {FormatNumber(currentY + 4)} m 543 {FormatNumber(currentY + 4)} l S");
            currentY -= 10;

            if (currentY < 130)
            {
                break;
            }
        }

        WriteText(
            content,
            52,
            108,
            10,
            "This electronically generated invoice is valid without signature.",
            0.35,
            0.35,
            0.35);

        return BuildPdf(content.ToString());
    }

    private static List<string> Wrap(string text, int maxCharsPerLine)
    {
        if (string.IsNullOrWhiteSpace(text))
        {
            return ["-"];
        }

        var words = text.Split(' ', StringSplitOptions.RemoveEmptyEntries);
        var lines = new List<string>();
        var current = new StringBuilder();

        foreach (var word in words)
        {
            var nextLength = current.Length == 0 ? word.Length : current.Length + 1 + word.Length;
            if (nextLength > maxCharsPerLine && current.Length > 0)
            {
                lines.Add(current.ToString());
                current.Clear();
            }

            if (current.Length > 0)
            {
                current.Append(' ');
            }

            current.Append(word);
        }

        if (current.Length > 0)
        {
            lines.Add(current.ToString());
        }

        return lines.Count == 0 ? ["-"] : lines;
    }

    private static void WriteText(
        StringBuilder content,
        double x,
        double y,
        int fontSize,
        string text,
        double r,
        double g,
        double b)
    {
        content.AppendLine("BT");
        content.AppendLine($"/F1 {fontSize} Tf");
        content.AppendLine($"{FormatNumber(r)} {FormatNumber(g)} {FormatNumber(b)} rg");
        content.AppendLine($"1 0 0 1 {FormatNumber(x)} {FormatNumber(y)} Tm");
        content.AppendLine($"({EscapePdf(text)}) Tj");
        content.AppendLine("ET");
    }

    private static string EscapePdf(string value) => value
        .Replace("\\", "\\\\")
        .Replace("(", "\\(")
        .Replace(")", "\\)");

    private static string FormatNumber(double value) => value.ToString("0.###", CultureInfo.InvariantCulture);

    private static byte[] BuildPdf(string streamContent)
    {
        var objects = new List<string>
        {
            "1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n",
            "2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj\n",
            "3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>\nendobj\n",
            $"4 0 obj\n<< /Length {Encoding.ASCII.GetByteCount(streamContent)} >>\nstream\n{streamContent}endstream\nendobj\n",
            "5 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>\nendobj\n"
        };

        var pdf = new StringBuilder();
        pdf.Append("%PDF-1.4\n");
        var offsets = new List<int> { 0 };
        foreach (var obj in objects)
        {
            offsets.Add(Encoding.ASCII.GetByteCount(pdf.ToString()));
            pdf.Append(obj);
        }

        var xrefStart = Encoding.ASCII.GetByteCount(pdf.ToString());
        pdf.Append($"xref\n0 {objects.Count + 1}\n");
        pdf.Append("0000000000 65535 f \n");
        foreach (var offset in offsets.Skip(1))
        {
            pdf.Append($"{offset:D10} 00000 n \n");
        }
        pdf.Append($"trailer\n<< /Size {objects.Count + 1} /Root 1 0 R >>\nstartxref\n{xrefStart}\n%%EOF");

        return Encoding.ASCII.GetBytes(pdf.ToString());
    }
}
