namespace GoldWalletSystem.Application.DTOs.Wallet;

public sealed record WalletDto(
    int Id,
    int UserId,
    decimal CashBalance,
    string CurrencyCode,
    IReadOnlyList<WalletAssetDto> Assets);

public sealed record WalletAssetDto(
    int Id,
    string AssetType,
    int? ProductId,
    string ProductName,
    string? ProductSku,
    string? ProductImageUrl,
    string Category,
    string MaterialType,
    string FormType,
    string? PurityKarat,
    string? PurityDisplayName,
    int? SellerId,
    string SellerName,
    decimal WeightValue,
    string WeightUnit,
    decimal Weight,
    string Unit,
    decimal Purity,
    int Quantity,
    decimal AverageBuyPrice,
    decimal CurrentMarketPrice,
    decimal AcquisitionSubTotalAmount,
    decimal AcquisitionFeesAmount,
    decimal AcquisitionDiscountAmount,
    decimal AcquisitionFinalAmount,
    int? LastTransactionHistoryId,
    int? SourceInvoiceId,
    int? InvoiceId,
    string? CertificateUrl,
    string? SourceInvestorName,
    bool IsDelivered,
    string Status,
    string? StatusDetails);
