using GoldWalletSystem.Domain.Enums;

namespace GoldWalletSystem.Application.DTOs.Products;

public sealed record ProductDto(
    int Id,
    string Name,
    string Sku,
    string Description,
    string ImageUrl,
    string VideoUrl,
    ProductCategory Category,
    ProductMaterialType MaterialType,
    ProductFormType FormType,
    string DisplayCategoryLabel,
    ProductPricingMode PricingMode,
    ProductPurityKarat PurityKarat,
    decimal PurityFactor,
    decimal WeightValue,
    ProductWeightUnit WeightUnit,
    decimal BaseMarketPrice,
    decimal AutoPrice,
    decimal FixedPrice,
    decimal SellPrice,
    decimal OfferPercent,
    decimal OfferNewPrice,
    ProductOfferType OfferType,
    bool IsHasOffer,
    int AvailableStock,
    bool isActive,
    int SellerId,
    string SellerName,
    string CurrencyCode,
    decimal BaseMarketPriceLocal,
    decimal SellPriceLocal);
